-- List the number of films per category.
select COUNT(film_id) as 'Numero de films', max(category_id) as 'categorias'
from film_category
group by category_id;

-- Retrieve the store ID, city, and country for each store.
select s.store_id,c.city,k.country from store as s
left join address as ad
on s.store_id = ad.address_id 

left join city as c
on ad.city_id = c.city_id

left join country as k
on c.country_id = k.country_id

-- Calculate the total revenue generated by each store in dollars.
SELECT s.store_id,sum(pm.amount) from store as s
LEFT JOIN staff as st
on s.store_id = st.store_id
left join payment as pm
on st.staff_id = pm.staff_id
group by s.store_id
/*  
Problemas con este ejercicio sin resolver, conforma  iba haciendo los left joins
me di cuenta en el left join de payment que solo me escupia el store id 1
posteriormente, tras ver con un compañero que teniamos lo mismo al hacer el group by
se soluciono y llama al store_id 1 y 2

*/   

